# Generated by Django 4.2.1 on 2023-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="Eth", max_length=5)),
                ("public_key", models.CharField(max_length=120, unique=True)),
                ("private_key", models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
