# Generated by Django 4.2.1 on 2023-05-19 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("balance_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                default="Eth",
                max_length=5,
                validators=[django.core.validators.RegexValidator(regex="^[Ee]th$")],
            ),
        ),
    ]
